apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-addons
spec:
  description: Cluster Addons Projects
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
    - namespace: 'kube-*'
      server: https://kubernetes.default.svc
    - namespace: 'argocd'
      server: https://kubernetes.default.svc