apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
spec:
  project: cluster-addons
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/karnzx/EKS-GitOps-CICD.git
    targetRevision: HEAD
    path: gitops/apps/addons/karpenter/helm
    helm:
      releaseName: karpenter
      valueFiles:
        - values.yaml
