apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
spec:
  project: cluster-addons
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    chart: karpenter
    repoURL: oci://public.ecr.aws/karpenter/karpenter
    targetRevision: 0.37.0
    helm:
      valuesObject:
        settings:
          clusterName: ProjectU
        serviceAccount:
          name: karpenter