apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-nodejs
spec:
  selector:
    matchLabels:
      app: dummy-nodejs
  template:
    metadata:
      labels:
        app: dummy-nodejs
    spec:
      containers:
      - name: dummy-nodejs
        image: public.ecr.aws/a9i2u6l7/dummy-nodejs:latest
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
        - containerPort: 3000

