apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
images:
- name: /a9i2u6l7/dummy-nodejs
- name: public.ecr.aws/a9i2u6l7/dummy-nodejs
  newName: public.ecr.aws/a9i2u6l7/dummy-nodejs
  newTag: 0f7b06c617d47203cdf8fb89935bef1f7eaa5ad0
